apiVersion: v1
kind: Service
metadata:
  name: avinginx-svc
  labels:
    app: avinginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: avinginx